language: php

php:
  - 5.2
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  
env:
  - DB=mysql
  - DB=mysqli
  - DB=pgsql
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite

sudo: false

matrix:
  allow_failures:
    - php: 5.2
    - php: hhvm
    - php: 7
  exclude:
    - php: hhvm
      env: DB=pgsql
    - php: hhvm
      env: DB=pdo/pgsql
    - php: 7
      env: DB=mysql
    - php: 5.2
      env: DB=sqlite
    - php: 5.2
      env: DB=pdo/sqlite